FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY target/OMSsystem-1.0.0.jar OMSsystem-1.0.0.jar

ENTRYPOINT ["/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home", "-jar", "OMSsystem-1.0.0.jar"]
